# Generated by Django 6.0.6 on 2026-06-25 19:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ad Name')),
                ('position', models.CharField(choices=[('header', 'Header'), ('home_left', 'Homepage – Left'), ('home_right', 'Homepage – Right'), ('article_top', 'Inside Article – Top'), ('article_bottom', 'Inside Article – Bottom'), ('sidebar', 'Sidebar')], db_index=True, max_length=50, verbose_name='Position')),
                ('adsense_code', models.TextField(help_text='Paste raw AdSense or custom HTML/JS here. Only trusted admin users should have access to this field.', verbose_name='AdSense Script / Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('position',), name='unique_active_ad_per_position')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this category site-wide.', verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in menus.', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='Select a parent to create a sub-category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from title.', max_length=255, unique=True, verbose_name='Slug')),
                ('author_name', models.CharField(blank=True, help_text='Auto-filled from the linked user; editable as a fallback.', max_length=150, verbose_name='Author Name')),
                ('short_description', models.TextField(blank=True, help_text='Summary shown on list/homepage cards.', verbose_name='Short Description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/', verbose_name='Featured Image')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Accessibility and image-SEO description.', max_length=255, verbose_name='Featured Image Alt Text')),
                ('image_caption', models.CharField(blank=True, help_text='Optional caption displayed below the featured image.', max_length=255, verbose_name='Image Caption')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('is_breaking_news', models.BooleanField(db_index=True, default=False, verbose_name='Breaking News')),
                ('reading_time', models.PositiveIntegerField(default=1, editable=False, help_text='Auto-calculated at 200 WPM; not editable directly.', verbose_name='Reading Time (minutes)')),
                ('views', models.PositiveBigIntegerField(default=0, editable=False, help_text='Incremented atomically via increment_views(); never set directly.', verbose_name='Views')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Set only to override the default canonical URL.', verbose_name='Canonical URL')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blogs', to='blog.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='blog_catego_slug_6fa4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', 'published_at'], name='blog_blog_status_b10001_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', 'status'], name='blog_blog_categor_a0ca1a_idx'),
        ),
    ]
