# Generated by Django 6.0.6 on 2026-06-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('home_left', 'Homepage - Left'), ('home_right', 'Homepage - Right'), ('article_top', 'Inside Article - Top'), ('article_bottom', 'Inside Article - Bottom'), ('sidebar', 'Sidebar')], db_index=True, max_length=50, verbose_name='Position'),
        ),
    ]
