# Generated by Django 6.0.6 on 2026-06-25 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_advertisement_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Blog View Record',
                'verbose_name_plural': 'Blog View Records',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
